/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mockup_Project;

import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS TBA
 */
public class mockup2 extends javax.swing.JFrame {

    data_tanaman list_tanaman = new data_tanaman();
    Tanaman pakis, bonsai;
    ArrayList<Tanaman> arrayTanaman = new ArrayList();
    boolean isDataTambah = false;
    int remainingBonsaiStock, remainingPakisStock;
    PembeliRegistrasi customer = new PembeliRegistrasi();
    Pembeli pembeli = new Pembeli();

    /**
     * Creates new form mock_up2
     */
    CardLayout cardMenu;

    public mockup2() {
        initComponents();
        cardMenu = (CardLayout) (jPanel2.getLayout());
    }

//    //method untuk mendapatkan inputan yang ada di keranjang
//    private void totalCartItem() {
//        Stack<Object> stackItem = new Stack();
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDashBoard1 = new javax.swing.JLabel();
        jLabelShop = new javax.swing.JLabel();
        jLabelCart = new javax.swing.JLabel();
        jLabelListTransacition = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMainPanel = new javax.swing.JPanel();
        jLabelGreeting1 = new javax.swing.JLabel();
        jPanelKeranjang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jShopPanel = new javax.swing.JPanel();
        jPanelItem1 = new javax.swing.JPanel();
        jLabelItem1 = new javax.swing.JLabel();
        jSpinnerItem1 = new javax.swing.JSpinner();
        jLabelItemName1 = new javax.swing.JLabel();
        jButtonTambahKeranjang1 = new javax.swing.JButton();
        jPanelItem2 = new javax.swing.JPanel();
        jLabelItem2 = new javax.swing.JLabel();
        jSpinnerItem2 = new javax.swing.JSpinner();
        jLabelItemName2 = new javax.swing.JLabel();
        jButtonTambahKeranjang2 = new javax.swing.JButton();
        jButtonCheckOut1 = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jButtonLoginResponse = new javax.swing.JButton();
        jLabelStock1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 235, 69));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelDashBoard1.setBackground(new java.awt.Color(91, 243, 126));
        jLabelDashBoard1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelDashBoard1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDashBoard1.setText("DASHBOARD ");
        jLabelDashBoard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDashBoard1MouseClicked(evt);
            }
        });

        jLabelShop.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabelShop.setForeground(new java.awt.Color(0, 0, 0));
        jLabelShop.setText("BELANJA");
        jLabelShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelShopMouseClicked(evt);
            }
        });
        jLabelShop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelShopKeyPressed(evt);
            }
        });

        jLabelCart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCart.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCart.setText("KERANJANG");
        jLabelCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCartMouseClicked(evt);
            }
        });

        jLabelListTransacition.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelListTransacition.setForeground(new java.awt.Color(0, 0, 0));
        jLabelListTransacition.setText("DAFTAR TRANSAKSI");
        jLabelListTransacition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelListTransacitionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCart)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelShop)
                                .addGap(12, 12, 12)))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelListTransacition)
                            .addComponent(jLabelDashBoard1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelDashBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabelShop, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jLabelCart)
                .addGap(166, 166, 166)
                .addComponent(jLabelListTransacition)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelShop.getAccessibleContext().setAccessibleName("jLabelShop\n");
        jLabelCart.getAccessibleContext().setAccessibleName("jLabelCart");

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabelGreeting1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelGreeting1.setText("Halo !! , Selamat datang di toko Heavy Rotation 17 \nSelamat berbelanjaaa!!!");

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabelGreeting1)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabelGreeting1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        jPanel2.add(jMainPanel, "card4");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Stock Tanaman", "Jumlah", "Harga ", "Jenis Tanaman"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitle.setText("TABEL CHECKOUT");

        javax.swing.GroupLayout jPanelKeranjangLayout = new javax.swing.GroupLayout(jPanelKeranjang);
        jPanelKeranjang.setLayout(jPanelKeranjangLayout);
        jPanelKeranjangLayout.setHorizontalGroup(
            jPanelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1229, Short.MAX_VALUE)
            .addGroup(jPanelKeranjangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelKeranjangLayout.setVerticalGroup(
            jPanelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeranjangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanelKeranjang, "card3");

        jPanelItem1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelItem1.setBackground(new java.awt.Color(148, 242, 120));
        jLabelItem1.setIcon(new javax.swing.ImageIcon("D:\\USD_JAVA_OOP\\PBOL\\Praktek\\src\\main\\java\\Images\\lodeh.jpg")); // NOI18N
        jLabelItem1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSpinnerItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinnerItem1KeyPressed(evt);
            }
        });

        jLabelItemName1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelItemName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelItemName1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelItemName1.setText("TANAMAN PAKIS");

        jButtonTambahKeranjang1.setText("Tambah");
        jButtonTambahKeranjang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahKeranjang1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelItem1Layout = new javax.swing.GroupLayout(jPanelItem1);
        jPanelItem1.setLayout(jPanelItem1Layout);
        jPanelItem1Layout.setHorizontalGroup(
            jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jSpinnerItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTambahKeranjang1)
                .addGap(48, 48, 48))
            .addGroup(jPanelItem1Layout.createSequentialGroup()
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItem1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabelItemName1))
                    .addGroup(jPanelItem1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelItem1Layout.setVerticalGroup(
            jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelItemName1)
                .addGap(24, 24, 24)
                .addGroup(jPanelItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTambahKeranjang1))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanelItem2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelItem2.setPreferredSize(new java.awt.Dimension(364, 175));

        jLabelItem2.setBackground(new java.awt.Color(148, 242, 120));
        jLabelItem2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSpinnerItem2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinnerItem2KeyPressed(evt);
            }
        });

        jLabelItemName2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelItemName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelItemName2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelItemName2.setText("TANAMAN BONSAI\n");

        jButtonTambahKeranjang2.setText("Tambah");
        jButtonTambahKeranjang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahKeranjang2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelItem2Layout = new javax.swing.GroupLayout(jPanelItem2);
        jPanelItem2.setLayout(jPanelItem2Layout);
        jPanelItem2Layout.setHorizontalGroup(
            jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabelItemName2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanelItem2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelItem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItem2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSpinnerItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTambahKeranjang2)
                .addGap(26, 26, 26))
        );
        jPanelItem2Layout.setVerticalGroup(
            jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItem2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelItemName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTambahKeranjang2))
                .addContainerGap())
        );

        jButtonCheckOut1.setText("CHECKOUT");
        jButtonCheckOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckOut1ActionPerformed(evt);
            }
        });

        jButtonRegister.setText("Register");
        jButtonRegister.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jButtonLoginResponse.setText("Login");
        jButtonLoginResponse.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonLoginResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginResponseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jShopPanelLayout = new javax.swing.GroupLayout(jShopPanel);
        jShopPanel.setLayout(jShopPanelLayout);
        jShopPanelLayout.setHorizontalGroup(
            jShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jShopPanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabelStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jShopPanelLayout.createSequentialGroup()
                .addContainerGap(752, Short.MAX_VALUE)
                .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCheckOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLoginResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(jShopPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jPanelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jShopPanelLayout.setVerticalGroup(
            jShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jShopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLoginResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCheckOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(702, Short.MAX_VALUE))
        );

        jButtonLoginResponse.getAccessibleContext().setAccessibleName("jButtonLogin");

        jPanel2.add(jShopPanel, "card2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1229, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerChecker(JSpinner spinner) {
        int spinnerChecker = (Integer) spinner.getValue();

        if (spinnerChecker <= 0) {
            JOptionPane.showMessageDialog(null, "Mohon masukkan jumlah barang anda !!!");
        }
    }

//    private void 

    private void jLabelShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShopMouseClicked
        // TODO add your handling code here:
        cardMenu.show(jPanel2, "card2");
    }//GEN-LAST:event_jLabelShopMouseClicked


    private void jLabelCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCartMouseClicked
        // TODO add your handling code here:
        cardMenu.show(jPanel2, "card3");
    }//GEN-LAST:event_jLabelCartMouseClicked

    private void jLabelShopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelShopKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabelShopKeyPressed

    private void jSpinnerItem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerItem1KeyPressed
        // TODO add your handling code here
    }//GEN-LAST:event_jSpinnerItem1KeyPressed

    private void jSpinnerItem2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerItem2KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jSpinnerItem2KeyPressed

    private void jLabelDashBoard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDashBoard1MouseClicked
        // TODO add your handling code here:
        cardMenu.show(jPanel2, "card4");
    }//GEN-LAST:event_jLabelDashBoard1MouseClicked

    private void jLabelListTransacitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelListTransacitionMouseClicked
        // TODO add your handling code here:
        cardMenu.show(jPanel2, "card5");
    }//GEN-LAST:event_jLabelListTransacitionMouseClicked

    private void jButtonCheckOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckOut1ActionPerformed
        // TODO add your handling code here:
        cardMenu.show(jPanel2, "card3");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int rowCount = model.getRowCount(); // Mendapatkan jumlah baris saat ini di tabel

        // Jumlah data yang Anda ingin tampilkan
        int desiredRowCount = arrayTanaman.size();

        // Jika jumlah baris saat ini tidak sama dengan jumlah data yang Anda inginkan, tambahkan atau hapus baris sesuai kebutuhan.
        if (rowCount < desiredRowCount) {
            // Tambahkan baris hingga jumlahnya sama dengan desiredRowCount
            for (int i = rowCount; i < desiredRowCount; i++) {
                Tanaman tanaman = arrayTanaman.get(i);

                if (jButtonTambahKeranjang1.isSelected()) {
                    Object[] row = {tanaman.getPlantName(), tanaman.getPrice(), remainingPakisStock};
                    model.addRow(row);
                }
                if (jButtonTambahKeranjang2.isFocusable()) {
                    Object[] row = {tanaman.getPlantName(), tanaman.getPrice(), remainingBonsaiStock};
                    model.addRow(row);
                }
            }
        } else if (rowCount > desiredRowCount) {
            // Hapus baris hingga jumlahnya sama dengan desiredRowCount
            for (int i = rowCount - 1; i >= desiredRowCount; i--) {
                model.removeRow(i);
            }
        }
    }//GEN-LAST:event_jButtonCheckOut1ActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        customer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        customer.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonLoginResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginResponseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonLoginResponseActionPerformed

    private void jButtonTambahKeranjang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahKeranjang1ActionPerformed
        arrayTanaman.add(list_tanaman.listTanaman.get(0));
        this.isDataTambah = true;
    }//GEN-LAST:event_jButtonTambahKeranjang1ActionPerformed

    private void jButtonTambahKeranjang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahKeranjang2ActionPerformed
        // TODO add your handling code here:
        arrayTanaman.add(list_tanaman.listTanaman.get(1));
        this.isDataTambah = true;
    }//GEN-LAST:event_jButtonTambahKeranjang2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mockup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mockup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mockup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mockup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mockup2().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckOut1;
    private javax.swing.JButton jButtonLoginResponse;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonTambahKeranjang1;
    private javax.swing.JButton jButtonTambahKeranjang2;
    private javax.swing.JLabel jLabelCart;
    private javax.swing.JLabel jLabelDashBoard1;
    private javax.swing.JLabel jLabelGreeting1;
    private javax.swing.JLabel jLabelItem1;
    private javax.swing.JLabel jLabelItem2;
    private javax.swing.JLabel jLabelItemName1;
    private javax.swing.JLabel jLabelItemName2;
    private javax.swing.JLabel jLabelListTransacition;
    private javax.swing.JLabel jLabelShop;
    private javax.swing.JLabel jLabelStock1;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelItem1;
    private javax.swing.JPanel jPanelItem2;
    private javax.swing.JPanel jPanelKeranjang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jShopPanel;
    private javax.swing.JSpinner jSpinnerItem1;
    private javax.swing.JSpinner jSpinnerItem2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
